### ISSUE TITLE
doesn't detabification break cross-patching?

### ISSUE THREAD

**Issue by rjbs** [evalEmpire/piledriver#26]
In 35ad8b794bc9598097f0f6fcd5271edb0636138b, all the C code is converted from spaces to tabs.  Doesn't that make it *much* more costly to import changes from bleadperl and, similarly, for bleadperl to crib improvements from piledriver?

**Comment by schwern** [comment]
Ideally, Perl 5 detabifies too. *hint hint, nudge nudge*

In reality, git has flags to ignore whitespace changes when merging and rebasing.  I've already done one rebasing of Piledriver onto a new Perl stable.  It wasn't perfect, but it was manageable.

Merge compatibility with Perl 5 is a concern, but there are bigger ones.  We're willing to do the one-time work necessary to fix conflicts rather than hold the whole project back.  For example, I went ahead with detabifying, but didn't normalize the indentation and bracing.  I really wanted to add an automatic beautifier, but that would cause a big and constant merge mess.  That's the sort of decision I'd like to see coordinated between the two projects.

Whitespace changes is probably the least of the merge worries.  There are broader changes we're making that are going to cause more difficult merge conflicts.  We'll see how it works out and deal with it when it happens.

On that note, I would like to start sending small changes upstream ASAP.
