### ISSUE TITLE
C99 vs. MSVC

### ISSUE THREAD

**Issue by rjbs** [evalEmpire/piledriver#27]
8ec36b4ef5e696b6c7f4ab4d11456c3333eef68f seems to state that piledriver will require C99.  Microsoft's compiler does not support much of C99.  Will piledriver still target compilation on Win32 under MSVC?

**Comment by johndeppe** [comment]
C99 is apparently supported in Visual Studio 2015?

Found this link on Wikipedia, which leads me to the belief: https://msdn.microsoft.com/en-us/library/hh409293.aspx

**Comment by schwern** [comment]
Yeah, [VS 2013 added basic C99 support and VS 2015 made it about as good as anyone else](https://en.wikipedia.org/wiki/C99#Implementations).

Right now the only C99 feature we're using is `inline` and that will have a compatibility macro (see #30), so from a practical standpoint things will still work on C90 compilers probably for a while.  But since we're replacing a lot of macros with inline functions (see #18) performance may suffer on super legacy systems.  It turns out Perl 5 already used inline, just not as aggressively as I mean to try. :grinning:

Piledriver's policy on environments is if we don't have a CI server for it, we don't support it.  This isn't a "fuck you" to odd environments, but rather a push for more CI servers.  I'm currently setting up Windows CI on appveyor.com which will do MinGW, VC2013 and VC2015.
